# Generated by Django 4.1.7 on 2023-04-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients_viewer", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="car",
            unique_together={("owner", "brand", "model", "year", "plate", "color")},
        ),
    ]
